steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/gcp-practise-346310/practise/ci-cd:2.0', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/gcp-practise-346310/practise/ci-cd:2.0']