version: '3.1'

services:
  api:
    image: europe-west1-docker.pkg.dev/gcp-practise-364610/prac/ci-cd:2.2
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://root:example@dev-db:27017/
      RANK: 2
      ESPADA: "Barragan Louisenbairn"
    depends_on:
      - dev-db
    ports:
      - 5000:5000

  dev-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
